language: android

android:
  components:
    - build-tools-21.1.1
    - build-tools-21.0.1
    - build-tools-20.0.0
    - extra

env:
  global:
    - LAWIS_LANGUAGES="android" # A space separated list of your repository's languages in the format that .travis.yml supports: http://docs.travis-ci.com/user/languages/
    - LAWIS_TIMEZONE="Europe/Helsinki"
    - LAWIS_SEC_TESTFLIGHT_API_TOKEN="e023db7e9b825321b2bc718807c332e8_MTk1MzY0MTIwMTQtMDctMDQgMDY6MjQ6MTEuOTQ1MTk1" # API token https://testflightapp.com/account/#api
    - LAWIS_SEC_TESTFLIGHT_TEAM_TOKEN="915994de316decaa03d10a67109666c6_NDE0MjAzMjAxNC0wOC0wMSAwODowODozMy45NzA5NjQ" # Team token https://testflightapp.com/dashboard/team/edit/?next=/api/doc/
    - LAWIS_SEC_HOCKEY_APP_ID="fb7ddc854d3fa1cbe7b050400a7c2dfe"
    - LAWIS_SEC_HOCKEY_APP_TOKEN="c3b65b6dbfbc46f2a863da3420b33bb7"

branches:
  only:
    - master
    - develop

cache:
  directories:
  - $HOME/.gradle/caches/

before_install: 
  - chmod +x gradlew
  - ./lawis/run.sh before_install

before_script: 
  - ./lawis/run.sh before_script

script:
    #debug build
   - ./gradlew assembleDevFDev
    #release for tests
   - ./gradlew assembleRelFRel
    #uat build
   - ./gradlew assembleUatFUat

after_success: 
  - ./lawis/run.sh after_success

after_failure: 
  - ./lawis/run.sh after_failure

after_script: 
  - ./lawis/run.sh after_script

before_deploy:
  - ./lawis/run.sh before_deploy

after_deploy:
  - ./lawis/run.sh before_deploy

notifications:
  hipchat:
    rooms:
      - a63f9d9b30c55820f37c87c15dd923@962005
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html
